package GUI.mainWindow;


import Client.Client;
import GUI.Panels.Bought;
import GUI.Panels.BuyAVignette;
import GUI.Panels.CardPayment;
import GUI.Panels.CheckTransactions;
import GUI.Panels.LogIn;
import GUI.Panels.Options;
import GUI.Panels.Payment;
import GUI.Panels.RechargeAPhoneCard;
import GUI.Panels.Recharged;
import GUI.Panels.Transfer;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import static sun.management.ConnectorAddressLink.export;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marina
 */

public class mainWindow extends javax.swing.JFrame {

    public static Client client;
    GridBagLayout layout = new GridBagLayout();
    static public LogIn p1;
    static Options p2;
    static CheckTransactions p3;
    static Payment p4;
    static CardPayment p5;
    static BuyAVignette p6;
    static Transfer p7;
    static RechargeAPhoneCard p8;
    static Recharged p9;
    static Bought p10;
    
    
    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
        p1 = new LogIn();
        p2 = new Options();
        p3 = new CheckTransactions();
        p4 = new Payment();
        p5 = new CardPayment();
        p6 = new BuyAVignette();
        p7 = new Transfer();
        p8 = new RechargeAPhoneCard();
        p9 = new Recharged();
        p10 = new Bought();
        
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        mainPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        
        c.gridx = 0;
        c.gridy = 0;
        mainPanel.add(p1, c);
        
        c.gridx = 0;
        c.gridy = 0;
        mainPanel.add(p2, c);
        
        c.gridx = 0;
        c.gridy = 0;
        mainPanel.add(p3, c);
        
        c.gridx = 0;
        c.gridy = 0;
        mainPanel.add(p4, c);
        
        c.gridx = 0;
        c.gridy = 0;
        mainPanel.add(p5, c);
        
        c.gridx = 0;
        c.gridy = 0;
        mainPanel.add(p6, c);
        
        c.gridx = 0;
        c.gridy = 0;
        mainPanel.add(p7, c);
        
        c.gridx = 0;
        c.gridy = 0;
        mainPanel.add(p8, c);
        
        c.gridx = 0;
        c.gridy = 0;
        mainPanel.add(p9, c);
        
        c.gridx = 0;
        c.gridy = 0;
        mainPanel.add(p10, c);
        
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        p5.setVisible(false);
        p6.setVisible(false);
        p7.setVisible(false);
        p8.setVisible(false);
        p9.setVisible(false);
        p10.setVisible(false);
       
    }
    
    public static void makep2Visible(){
        p2.setVisible(true);
    }
    
    public static void makep3Visible(){
        p3.setVisible(true);
    }
    
    public static void makep4Visible(){
        p4.setVisible(true);
    }
    
    public static void makep5Visible(){
        p5.setVisible(true);
    }
    
    public static void makep6Visible(){
        p6.setVisible(true);
    }
    
    public static void makep7Visible(){
        p7.setVisible(true);
    }
    
    public static void makep8Visible(){
        p8.setVisible(true);
    }
    
    public static void makep9Visible(){
        p9.setVisible(true);
    }
    
    public static void makep10Visible(){
        p10.setVisible(true);
    }
    
    public void start(Client client){
        this.client = client;
        new mainWindow().setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 255));
        jLabel1.setText("Online Banking");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("x");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new mainWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
